server:
  port: 8761
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  serverUrl:
    defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: false
    ip-address: 10.10.10.1
    hostname: ttt
